NakaSiteMVC/Models/ErrorViewModel.cs
using System;

namespace NakaSiteMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NakaSiteMVC/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NakaSiteMVC.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult About()
        {
            return View();
        }
    }
}

NakaSiteMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NakaSiteMVC.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace NakaSiteMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NakaSiteMVC/Controllers/MaterialGaleryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NakaSiteMVC.Controllers
{
    public class MaterialGaleryController : Controller
    {
        public IActionResult UaStone()
        {
            return View();
        }

        public IActionResult ImpStone()
        {
            return View();
        }

        public IActionResult Marmur()
        {
            return View();
        }

        public IActionResult Kvarz()
        {
            return View();
        }
    }
}

NakaSiteMVC/Controllers/ProductGaleryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NakaSiteMVC.Controllers
{
    public class ProductGaleryController : Controller
    {
        public IActionResult Pidvikonniki()
        {
            return View();
        }

        public IActionResult Parkany()
        {
            return View();
        }
        
        public IActionResult Garadychi()
        {
            return View();
        }      
        
        public IActionResult Stilnici()
        {
            return View();
        }  
        
        public IActionResult Dvory()
        {
            return View();
        }     
        
        public IActionResult Tables()
        {
            return View();
        }        
        public IActionResult Fundamenty()
        {
            return View();
        }
    }
}

NakaSiteMVC/Views/About/About.cshtml
@{
    ViewData["Title"] = "About us";
}

<link href="~/css/ProductGalery.css" rel="stylesheet" />
<section>
    <div class="container-fluid">
        <div class="row">
            <div class="galery_ware col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 text-center pb-5">
                <h1>Про нас</h1>
                <div class="about text-left mb-5 p-5">
                    
                    <p1>
                        <a asp-action="Index" asp-controller="Home" class="navbar-brand pl-3">
                            <img src="~/image/Frame 1.png" width="110" height="70" class="logo " />

                        </a>- на ринку з 2010 року, за цей довгий і не легкий час ми стикалися з виробами різної складності, від простих підвікоників до різноманітних форм за макетами клієнтів, але до будь-якого виробу ми завжди ставимося з інтузіазмом та відповідальністю. На власному виробництві ми виготовляємо міцні, якісні, естетично бездоганні вироби з каменю. Виконуємо на замовлення найсміливіші і нестандартні проекти по каменю. Тому ми можемо сміливо назвати себе професіоналами свого діла і з гордістю сказати що наша компанія виготовить вироби будь-якого рівня складності, маючи в своєму розпорядженні для цього все неодхідне та потужне обладнаня  та штат кваліфікованих фахівців по роботі з каменем.
                    </p1>
                </div>
            </div>
        </div>
        </div>
</section>

NakaSiteMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<section>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="~/image/stilnici/k4.jpg" />
            <div class="carousel-caption">
                <h4>Вироби з граніту, мрамору та кварциту</h4>
                <p4>Ми виготовляємо вироби різної складності, завдяки 10-ти річному досвіду роботи</p4>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="content col-12 text-center my-5">
                <h6>Види каменю</h6>
            </div>
            <div class="stoun_list col-sm-12 col-md-6 col-lg-3 col-xl-3">
                <a asp-controller="MaterialGalery" asp-action="UaStone">
                    <img class="img-fluid" alt="" src="~/image/materials/jatkovka2.jpg" />
                    <div class="caption text-center">
                        <h2>Жатківка</h2>
                        <p6>Український грантіт</p6>
                    </div>
                </a>
            </div>
            <div class="stoun_list  col-sm-12 col-md-6 col-lg-3 col-xl-3">
                <a asp-controller="MaterialGalery" asp-action="ImpStone">
                    <img class="img-fluid" alt="" src="~/image/materials/newwiscount.jpg" />
                    <div class="caption text-center">
                        <h2>New Wiscount</h2>
                        <p6>Імпортний грантіт</p6>
                    </div>
                </a>
            </div>
            <div class="stoun_list col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 p-3">
                <a asp-controller="MaterialGalery" asp-action="Marmur">
                    <img class="img-fluid" alt="" src="~/image/materials/orosei.jpg" />
                    <div class="caption text-center">
                        <h2>Orosei</h2>
                        <p6>Мрамур</p6>
                    </div>
                </a>
            </div>
            <div class="stoun_list col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 p-3">
                <a asp-controller="MaterialGalery" asp-action="Kvarz">
                    <img class="img-fluid" alt="" src="~/image/materials/kvarc_gray.jpg" />
                    <div class="caption text-center">
                        <h2>Gray</h2>
                        <p6>Кварцит</p6>
                    </div>
                </a>
            </div>

            <div class="col-12 d-flex px-5  justify-content-end">
                <div class="catalog">
                    <a class="catalog_item mt-5 dropdown-toggle justify-content-end" href="" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Каталог каменю
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item my-1" asp-controller="MaterialGalery" asp-action="UaStone">
                            <i class="fab fa-sketch"></i>
                            Український граніт
                        </a>
                        <a class="dropdown-item my-1" asp-controller="MaterialGalery" asp-action="ImpStone">
                            <i class="fab fa-sketch"></i>
                            Імпортний граніт
                        </a>
                        <a class="dropdown-item my-1" asp-controller="MaterialGalery" asp-action="Marmur">
                            <i class="fab fa-sketch"></i>
                            Мрамур
                        </a>
                        <a class="dropdown-item my-1" asp-controller="MaterialGalery" asp-action="Kvarz">
                            <i class="fab fa-sketch"></i>
                            Кварцит
                        </a>
                    </div>
                </div>
            </div>

            <div class="row contect_contact col-12 my-5 mx-0">

                <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
                    <div class="contact text-center py-5">
                        <ul>
                            Наші контакти:
                            <li class="contact_item p-2"><i class="fas fa-phone-alt p-2"></i>+380978552687</li>
                            <li class="contact_item p-2"><i class="fas fa-phone-alt p-2"></i>+380683038014</li>
                            <li class="contact_item p-2"><i class="fas fa-phone-alt p-2"></i>+380976838585</li>
                        </ul>


                    </div>

                </div>

                <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
                    <div class="h_work text-center py-5">
                        <ul>
                            Графік роботи:
                            <li class="h_work_item p-2"><i class="far fa-calendar-alt p-2"></i>Пн - Сб</li>
                            <li class="h_work_item p-2"><i class="far fa-clock p-2"></i>09:00 - 21:00</li>
                            <li class="h_work_item p-2"><i class="far fa-calendar-alt p-2"></i>Нд - вихідний</li>
                        </ul>


                    </div>
                </div>
            </div>

            <div class="content col-12 text-center my-5">
                <h6>Наші вироби</h6>
            </div>
            <div class="stoun_list col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 p-3">
                <a asp-controller="ProductGalery" asp-action="Parkany">
                    <img class="img-fluid" alt="" src="~/image/parkany/i30.jpg" />
                    <div class="caption text-center">
                        <h2>Paradis</h2>
                        <p6>Паркан</p6>
                    </div>
                </a>
            </div>

            <div class="stoun_list col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 p-3">
                <a asp-controller="ProductGalery" asp-action="Parkany">
                    <img class="img-fluid" alt="" src="~/image/dvody/4.jpg" />
                    <div class="caption text-center">
                        <h2>Жатківка</h2>
                        <p4>Подвір'я</p4>
                    </div>
                </a>
            </div>

            <div class="stoun_list col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 p-3">
                <a asp-controller="ProductGalery" asp-action="Parkany">
                    <img class="img-fluid" alt="" src="~/image/garadychi/m38.jpg" />
                    <div class="caption text-center">
                        <h2>Karara</h2>
                        <p6>Сходи</p6>
                    </div>
                </a>
            </div>

            <div class="stoun_list col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 p-3">
                <a asp-controller="ProductGalery" asp-action="Parkany">
                    <img class="img-fluid" alt="" src="~/image/parkany/u4.jpg" />
                    <div class="caption text-center">
                        <h2>Межерічка</h2>
                        <p4>Паркан</p4>
                    </div>
                </a>
            </div>

            <div class="col-12 d-flex px-5  justify-content-end">
                <div class="catalog">
                    <a class="catalog_item mt-5 dropdown-toggle justify-content-end" href="" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Галерея виробів
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item mt-1 mb-1 " asp-controller="ProductGalery" asp-action="Pidvikonniki">
                            <i class="fab fa-sketch"></i>
                            Підвіконки
                        </a>
                        <a class="dropdown-item mt-1 mb-1" asp-controller="ProductGalery" asp-action="Parkany">
                            <i class="fab fa-sketch"></i>
                            Паркани
                        </a>
                        <a class="dropdown-item" asp-controller="ProductGalery" asp-action="Stilnici">
                            <i class="fab fa-sketch"></i>
                            Стільниці
                        </a>
                        <a class="dropdown-item mt-1 mb-1" asp-controller="ProductGalery" asp-action="Garadychi">
                            <i class="fab fa-sketch"></i>
                            Сходи
                        </a>
                        <a class="dropdown-item mt-1 mb-1" asp-controller="ProductGalery" asp-action="Dvory">
                            <i class="fab fa-sketch"></i>
                            Подвір'я
                        </a>
                        <a class="dropdown-item mt-1 mb-1" asp-controller="ProductGalery" asp-action="Tables">
                            <i class="fab fa-sketch"></i>
                            Столи
                        </a>
                        <a class="dropdown-item mt-1 mb-1" asp-controller="ProductGalery" asp-action="Fundamenty">
                            <i class="fab fa-sketch"></i>
                            Фундамент
                        </a>
                    </div>
                </div>
            </div>

            <div class=" contect_contact my-5 col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
                <div class="contact text-center py-5">
                    <ul>
                        Наші послуги:
                        <li class="contact_item p-2"><i class="fas fa-pencil-ruler p-2"></i>Заміри</li>
                        <li class="contact_item p-2"><i class="fas fa-drafting-compass p-2"></i>Виготовлення</li>
                        <li class="contact_item p-2"><i class="fas fa-truck-loading p-2"></i>Доставка</li>
                        <li class="contact_item" p-2><i class="fas fa-ruler-combined p-2"></i>Монтаж</li>
                    </ul>


                </div>

            </div>

            <div class="contect_contact my-5 col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
                <div class="h_work text-center py-5">
                    <ul>
                        Переваги нашої продукції:
                        <li class="h_work_item p-2"><i class="fas fa-mountain p-2"></i>Полірованні і термо-обробленні поверхні</li>
                        <li class="h_work_item p-2"><i class="fas fa-palette p-2"></i>Візерунки які створенні природою</li>
                        <li class="h_work_item p-2"><i class="fas fa-recycle p-2"></i>100% екологічний камінь</li>
                        <li class="h_work_item p-2"><i class="fas fa-tools p-2"></i>Вічний термін служби</li>
                    </ul>


                </div>
            </div>
        </div>


        <div class="content col-12 text-center">
            <h6>Наші гарантії:</h6>
        </div>
        <div class="row m-5">
            <ul class="guarantee text-center col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4">
                <li class="guarantee_item"> <i class="far fa-check-circle p-1"></i>Якості</li>
                <p1>Ми працюємо тільки з якісною сировиною, здобутим в кращих кар'єрах.</p1>
            </ul>
            <ul class="guarantee text-center col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4">
                <li class="guarantee_item"> <i class="far fa-check-circle p-1"></i>Заміни</li>
                <p1>Ми швидко замінимо бракований або пошкодженний під час перевезення виріб</p1>
            </ul>
            <ul class="guarantee text-center col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
                <li class="guarantee_item"> <i class="far fa-check-circle p-1"></i>Ціни</li>
                <p1>Ми пропонуємо кращу ціну! Знайдете ціну нижче - напишіть нам, і ми зробимо Вам більш вигідну пропозицію.</p1>
            </ul>
        </div>
    </div>
</section>

NakaSiteMVC/Views/MaterialGalery/ImpStone.cshtml
@{
    ViewData["Title"] = "Імпортний граніт";
}

<link href="~/css/ProductGalery.css" rel="stylesheet" />
<section>
    <div class="container-fluid">
        <div class="row">
            <div class="galery_ware col-12 col-sm-12 col-md12 col-lg-12 col-xl-12 text-center pb-5">
                <h1>Імпортний граніт</h1>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container-fluid">
        <div class="tz-gallery">
            <div class="row pt-5">
                <div class="gallery_product col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3">
                    <div class="thumbnail p-3">
                        <a class="lightbox" href="~/image/materials/paradis.jpg">
                            <img class="img-fluid" alt="" src="~/image/materials/paradis.jpg" />
                        </a>
                        <div class="caption text-center">
                            <h3>Paradis</h3>
                        </div>
                    </div>
                </div>
                <div class="gallery_product col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3">
                    <div class="thumbnail p-3">
                        <a class="lightbox" href="~/image/materials/newwiscount.jpg">
                            <img class="img-fluid" alt="" src="~/image/materials/newwiscount.jpg" />
                        </a>
                        <div class="caption text-center">
                            <h3>New Viscount</h3>
                        </div>
                    </div>
                </div>
                <div class="gallery_product col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3">
                    <div class="thumbnail p-3">
                        <a class="lightbox" href="~/image/materials/fantasi.jpg">
                            <img class="img-fluid" alt="" src="~/image/materials/fantasi.jpg" />
                        </a>
                        <div class="caption text-center">
                            <h3>Fantasi</h3>
                        </div>
                    </div>
                </div>
               
                <div class="gallery_product col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3">
                    <div class="thumbnail p-3">
                        <a class="lightbox" href="~/image/materials/romaniagray.jpg">
                            <img class="img-fluid" alt="" src="~/image/materials/romaniagray.jpg" />
                        </a>
                        <div class="caption text-center">
                            <h3>Romania Gray</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

NakaSiteMVC/Views/MaterialGalery/Kvarz.cshtml
@{
    ViewData["Title"] = "Кварцит";
}

<link href="~/css/ProductGalery.css" rel="stylesheet" />
<section>
    <div class="container-fluid">
        <div class="row">
            <div class="galery_ware col-12 col-sm-12 col-md12 col-lg-12 col-xl-12 text-center pb-5">
                <h1>Кварцит</h1>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="container-fluid">
        <div class="tz-gallery">
            <div class="row pt-5">
                <div class="gallery_product  col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3">
                    <div class="thumbnail p-3">
                        <a class="lightbox" href="~/image/materials/kvarc_gray.jpg">
                            <img class="img-fluid" alt="" src="~/image/materials/kvarc_gray.jpg" />
                        </a>
                        <div class="caption text-center">
                            <h3>White</h3>
                        </div>
                    </div>
                </div>
                <div class="gallery_product col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3">
                    <div class="thumbnail p-3">
                        <a class="lightbox" href="~/image/materials/kvarc_gray.jpg">
                            <img class="img-fluid" alt="" src="~/image/materials/kvarc_gray.jpg" />
                        </a>
                        <div class="caption text-center">
                            <h3>Gray</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

NakaSiteMVC/Views/ProductGalery/Pidvikonniki.cshtml
@{
    ViewData["Title"] = "Підвіконники";
}

<link href="~/css/ProductGalery.css" rel="stylesheet" />
<section>
    <div class="container-fluid">
        <div class="row">
            <div class="galery_ware col-12 col-sm-12 col-md12 col-lg-12 col-xl-12 text-center pb-5">
                <h1>Підвіконники</h1>
                <p1>-це обов'язковий елемент конструкції віконного блоку, красиве і стильне доповнення інтер'єру приміщення</p1>
            </div>
        </div>
    </div>
</section>
<section>
    <div class="container-fluid">
        <div class="tz-gallery">
            <div class="row ">
                <div class="text-center pt-5 col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
                    <button class="filter-button" data-filter="all">Всі</button>
                    <button class="filter-button" data-filter="category1">Український граніт</button>
                    <button class="filter-button" data-filter="category2">Імпортний граніт</button>
                    <button class="filter-button" data-filter="category3">Мрамур</button>
                </div>
                <div class="gallery_product filter col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 category1">
                    <div class="thumbnail p-3">
                        <a class="lightbox" href="~/image/pidvikonniki/u1.jpg">
                            <img class="stone_list img-fluid" alt="" src="~/image/pidvikonniki/u1.jpg" />
                        </a>
                        <div class="caption text-center">
                            <h3>Жатківка</h3>
                        </div>
                    </div>
                </div>
                <div class="gallery_product filter col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 category1">
                    <div class="thumbnail p-3">
                        <a class="lightbox" href="~/image/pidvikonniki/u2.jpg">
                            <img class="stone_list img-fluid" alt="" src="~/image/pidvikonniki/u2.jpg" />
                        </a>
                        <div class="caption text-center">
                            <h3>Жатківка</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
</section>

NakaSiteMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ApshaGran - вироби з граніту, мрамору та кварциту</title>
    <link rel="icon" href="~/image/Dribbble shot - 4.png" /> 
    <link rel="stylesheet" href="~/fontawesome/css/all.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/home.css" />
</head>


<body>
    <nav class="navbar navbar-default navbar-expand-xl" style="background-color:rgba(255, 255, 255, 0.3)">
        <a asp-action="Index" asp-controller="Home" class="navbar-brand pl-3 flex-fill">
            <img src="~/image/Dribbble shot - 4.png" width="130" height="90" class="logo" />
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span><i class="fas fa-bars"></i></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">

            <ul class="nav fa-pull-right justify-content-center pr-3 pl-3 ">

                <li class="nav-item dropdown text-center  pr-3 pl-3 pt-1 ">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Каталог каменю
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item mt-1 mb-1" asp-controller="MaterialGalery" asp-action="UaStone">
                            <i class="fab fa-sketch"></i>
                            Український граніт
                        </a>
                        <a class="dropdown-item mt-1 mb-1" asp-controller="MaterialGalery" asp-action="ImpStone">
                            <i class="fab fa-sketch"></i>
                            Імпортний граніт
                        </a>
                        <a class="dropdown-item mt-1 mb-1" asp-controller="MaterialGalery" asp-action="Marmur">
                            <i class="fab fa-sketch"></i>
                            Мрамур
                        </a>
                        <a class="dropdown-item mt-1 mb-1" asp-controller="MaterialGalery" asp-action="Kvarz">
                            <i class="fab fa-sketch"></i>
                            Кварцит
                        </a>
                    </div>
                </li>
                <li class="nav-item dropdown text-center  pr-3 pl-3 ">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Галерея виробів
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item mt-1 mb-1 " asp-controller="ProductGalery" asp-action="Pidvikonniki">
                            <i class="fab fa-sketch"></i>
                            Підвіконки
                        </a>
                        <a class="dropdown-item mt-1 mb-1" asp-controller="ProductGalery" asp-action="Parkany">
                            <i class="fab fa-sketch"></i>
                            Паркани
                        </a>
                        <a class="dropdown-item" asp-controller="ProductGalery" asp-action="Stilnici">
                            <i class="fab fa-sketch"></i>
                            Стільниці
                        </a>
                        <a class="dropdown-item mt-1 mb-1" asp-controller="ProductGalery" asp-action="Garadychi">
                            <i class="fab fa-sketch"></i>
                            Сходи
                        </a>
                        <a class="dropdown-item mt-1 mb-1" asp-controller="ProductGalery" asp-action="Dvory">
                            <i class="fab fa-sketch"></i>
                            Подвір'я
                        </a>
                        <a class="dropdown-item mt-1 mb-1" asp-controller="ProductGalery" asp-action="Tables">
                            <i class="fab fa-sketch"></i>
                            Столи
                        </a>
                        <a class="dropdown-item mt-1 mb-1" asp-controller="ProductGalery" asp-action="Fundamenty">
                            <i class="fab fa-sketch"></i>
                            Фундамент
                        </a>
                    </div>
                </li>
                <li class="nav-item text-center pr-3 pl-3 pb-1">
                    <a class="nav-link" asp-controller="About" asp-action="About">Про&nbsp;нас</a>
                </li>
            </ul>
        </div>
    </nav>


    <main role="main" class="pb-3 flex">
        @RenderBody()
    </main>

    <footer class="border-top border-dark footer">
        <div class="container-fluid">
            <div class="row">
                <div class="footer_main d-flex  col-12">
                    <div class="footer_item d-flex align-items-center justify-content-center col-sm-2 col-md-4 col-lg-4 col-xl-4">
                        <div class="footer_content">
                            <a asp-action="Index" asp-controller="Home" class="navbar-brand pl-3">
                                <img src="~/image/Frame 1.png" width="110" height="70" class="logo " />

                            </a>
                            <div class="footer_item_company">&copy;2021 - ApshaGran</div>

                        </div>
                    </div>

                    <div class="g_map d-flex align-items-center justify-content-around col-4"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d52103.89411495572!2d23.802952417631577!3d48.01094859897684!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4737a2d0a8a0483f%3A0x14a2d4ac496add21!2z0J3QuNC20L3Rj9GPINCQ0L_RiNCwLCDQl9Cw0LrQsNGA0L_QsNGC0YHQutCw0Y8g0L7QsdC70LDRgdGC0Yw!5e1!3m2!1sru!2sua!4v1636749055389!5m2!1sru!2sua" width="400" height="150" style="border:0;" allowfullscreen="" loading="lazy"></iframe></div>

                    <div class="footer_item d-flex justify-content-center align-items-center col-sm-10 col-md-4 col-lg-4 col-xl-4">
                        <div class="footer_item">
                            <a><i class="fab fa-viber p-2"></i></a>
                            <a href="https://instagram.com/apshagran?utm_medium=copy_link"> <i class="fab fa-instagram p-2"></i></a>
                            <a><i class="fab fa-facebook-square p-2"></i></a>
                            <a><i class="fab fa-whatsapp p-2"></i></a>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </footer>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>
    <script>
        baguetteBox.run('.tz-gallery');
    </script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>



</html>